apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: epayfrontend-pvc
  labels:
    name: epayfrontendpvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

